// <auto-generated />
namespace IT431Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbReservLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbReservLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201704280041125_DbReservLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
